### ISSUE TITLE
Running Jasper Tomcat on a different port

### ISSUE THREAD

**Issue by jamesnyika** [bitnami/bitnami-docker-jasperreports#100]
Feature request: Currently, the docker image off the hub for Jasper 7 seems to overwrite any server.xml files I provide to the container through the docker volume flag. It seems to overwrite my server.xml each time I start the container. Can the team consider adding an environment variable to specify a Jasper listening port

eg. -e JASPER_TOMCAT_PORT 7070

 This might be done as part of the SSL feature request on this list as well ?

**Comment by migruiz4** [comment]
Hi @jamesnyika,

Thank you very much for your suggestions! I have created an internal task to implement this feature and https://github.com/bitnami/bitnami-docker-jasperreports/issues/79.

Meanwhile, if you'd like to contribute by making any changes to the JasperReport image, feel free to send a PR and we will be very happy to review it and help you with anything if needed.

**Comment by jamesnyika** [comment]
Thank you @migruiz4 - I appreciate it very much. I do not have a PR to offer up... but I appreciate your efforts and the consideration

**Comment by migruiz4** [comment]
Thank you for your understanding @jamesnyika.

We will keep you updated about any changes to your feature request.

**Comment by jamesnyika** [comment]
Additional Comment: Alternative option here would be to offer a way to specify my own server.xml file for the Tomcat server to use. Currently, the container overwrites the server.xml (by generating it afresh each time). I tried providing my own but it is always overwritten. If we can provide a switch that allows it to NOT overwrite / generate a server.xml, this would be a good temporary fix.

**Comment by jamesnyika** [comment]
UPDATE: so it turns out that no additional fix might be needed. I would love for the Bitnami team to confirm this. But I ran the following test

I set up a mariadb container - as normal except I did not allow passwords to be empty

```bash

## create  db volume
docker volume create --name mariadb_data

## network 
docker network create jasperreports-network

## create  container
docker create \
  --hostname mariadb \
  --name MDB \
  --env ALLOW_EMPTY_PASSWORD=no \
  --env MARIADB_USER=bn_jasperreports \
  --env MARIADB_PASSWORD=bitnami \
  --env MARIADB_DATABASE=bitnami_jasperreports \
  --network jasperreports-network \
  --volume mariadb_data:/bitnami/mariadb \
  bitnami/mariadb:latest

## start container
docker start MDB

```

I then set up the jasper container but I included a flag that is usually on Bitnami's Tomcat Container to change port - notice the port to use now is 6060

```bash 

## data vol
docker volume create --name jasperreports_data

## create container
docker create \
  --name JSR \
  --hostname jasperserver \
  -p 6060:6060 \
  -e TOMCAT_HTTP_PORT_NUMBER=6060 \
  -e ALLOW_EMPTY_PASSWORD=no \
  -e JASPERREPORTS_DATABASE_USER=bn_jasperreports \
  -e JASPERREPORTS_DATABASE_PASSWORD=bitnami \
  -e JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports \
  --network jasperreports-network \
  --volume jasperreports_data:/bitnami/jasperreports \
  bitnami/jasperreports:latest

## run container
docker start JSR

```

And once the server was done setting up and running - voila! 
It is now accessible on 6060. Looks like bitnami tomcat settings are recognized and used in this container as well... 

<img width="1115" alt="Screen Shot 2021-09-28 at 2 44 37 PM" src="https://user-images.githubusercontent.com/6818081/135147089-26a9600f-b037-473a-b35d-b17aeacde19f.png">


So this solves it for me.. but hope it helps others.

Request for the Bitnami team: Please add a reference in the documentation to the TOMCAT environment variables as being usable here to if you want to customize the behavior of the Jasper Tomcat Server. I wonder if this works for other containers too ? .... hmmm....

**Comment by juan131** [comment]
Hi @jamesnyika 

You're totally right, some of the `TOMCAT_XXX` env. variables are also available in this container. As you can see in the [container's entrypoint](https://github.com/bitnami/bitnami-docker-jasperreports/blob/master/7/debian-10/rootfs/opt/bitnami/scripts/jasperreports/entrypoint.sh#L22) the Tomcat's [setup.sh](https://github.com/bitnami/bitnami-docker-jasperreports/blob/master/7/debian-10/rootfs/opt/bitnami/scripts/tomcat/setup.sh) script is invoked:

```
    TOMCAT_ENABLE_AUTH="${TOMCAT_ENABLE_AUTH:-no}" /opt/bitnami/scripts/tomcat/setup.sh
```

This script makes use of the env. variables defined in the [tomcat-env.sh](https://github.com/bitnami/bitnami-docker-jasperreports/blob/master/7/debian-10/rootfs/opt/bitnami/scripts/tomcat-env.sh) script and the functions define in the [libtomcat.sh](https://github.com/bitnami/bitnami-docker-jasperreports/blob/master/7/debian-10/rootfs/opt/bitnami/scripts/libtomcat.sh) library.

> Request for the Bitnami team: Please add a reference in the documentation to the TOMCAT environment variables as being usable here to if you want to customize the behavior of the Jasper Tomcat Server

Noted! We should definitely document the env. variables affecting Tomcat that are exposed in this container. I'll create a task to ensure every app in the catalog using Tomcat include these sections in the README.md.

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-jasperreports#community-supported-solution) since this asset was marked as a "Community supported solution". At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
