### ISSUE TITLE
Timezone-related changes are not reflected in a jasperreport image running in an openshift environment

### ISSUE THREAD

**Issue by Haydar-Rap** [bitnami/bitnami-docker-jasperreports#102]
By default, sequential file names by timestamp and timestamp pattern changes are not reflected on the "new schedule" screen.

Jasper report docker bitnami image : 7.5.0-debian-10-r43

https://knowledge.broadcom.com/external/article/214320/jasperserver-scheduled-reports-default.html

I'm throwing the operations specified in the link below into the container by providing operations in the Dockerfile and app-entrypoint.sh file.

app-entrypoind.sh file
cp /jobModel.js /opt/bitnami/jasperreports/optimized-scripts/scheduler/model/jobModel.js 
OR
​​​​​​​cp /jobModel.js /opt/bitnami/jasperreports/scripts/scheduler/model/jobModel.js
AND
export JAVA_OPTS="$JAVA_OPTS -Duser.timezone=Europa/Istanbul"
DockerFile
ADD ./jobModel.js /jobModel.js
OR 
COPY jobModel.js /opt/bitnami/jasperreports/optimized-scripts/scheduler/model/jobModel.js

​​​​​​​After changing the relevant files, I am experimenting as follows. But after the container starts, the related files and the changes in it are reflected, but when the jasperreport stands up, I see that the change is not reflected. How can I overcome this situation? I couldn't find the solution.

**Comment by miguelaeh** [comment]
Hi @Haydar-Rap ,
I was not able to find the `jobModel.js` in the webapps folder as described in the thread. Could it be possible that the file is only available on jasperserver-pro ?

**Comment by Haydar-Rap** [comment]
Hi @miguelaeh ,
When I search on the container as below, there are already files in the relevant directory. I think the .js file is being moved to the optimized folder by rendering on node. But since the jasperreport service in the container starts, the change I made is not reflected. Unfortunately I am stuck because I do not have the possibility to restart the service in docker container.
find / -type f -name jobModel.js

**Comment by miguelaeh** [comment]
Hi @Haydar-Rap ,
I saw you copied the file manually, sorry it was my confusion.
Ddo you have a link to the official docs instead of a forum?

**Comment by Haydar-Rap** [comment]
Thank you for your help. It didn't happen because I typed wrong letter in defining environment on Dockerfile. I fixed it now. Problem is solved.

ENV JAVA_OPTS="$JAVA_OPTS -Duser.timezone=Europe/Istanbul"

**Comment by miguelaeh** [comment]
I am glad you solved it! Thank you for letting us know
