### ISSUE TITLE
Is there a way to disable encryption of data and remove the need of keys?

### ISSUE THREAD

**Issue by aharper273** [bitnami/bitnami-docker-jasperreports#103]
It has been an incredibly hassle to migrate DBs and Jasper instances because of the way it requires keys. I saw a previous issue asking how to appropriately add the keys for importing (which i have yet to successfully do) but I don't need the encryption to begin with at this point. Is there a configuration to just remove the encryption altogether?

**Comment by pablogalegoc** [comment]
Hi @aharper273!

From our side, there is not. These [here](https://github.com/bitnami/bitnami-docker-jasperreports/blob/master/7/debian-10/rootfs/opt/bitnami/scripts/jasperreports-env.sh#L23-L51) are all the environment variables that we (Bitnami) provide in the container to toggle configuration parameters. The question is if the upstream project (JasperReports) even allows it, and from a quick look to their documentation I don't think they do.
