### ISSUE TITLE
Way to import .jrsks and .jrsksp keys without them being overwritten on start up?

### ISSUE THREAD

**Issue by aharper273** [bitnami/bitnami-docker-jasperreports#105]
When I attempt to add the .jrsks and .jrsksp keys to the docker container on start up, they get overwritten by the jasperserver startup scripts. I am unsure what the appropriate method is to add these keys so I can more easily migrate between instances if needed.

I have attempted to make this work by copying the keys to ```/opt/bitnami/jasperreports```. 

Attempts to mount the keys seem to cause issues.

Is there a documented best way to do this?

**Comment by juan131** [comment]
Hi @aharper273 

You might want to explore the possibility of mounting a custom shell script at `/docker-entrypoint-init.d` and use it to copy your custom keys **after** JasperServer has been initialized. Would that work for you? See:

- https://github.com/bitnami/bitnami-docker-jasperreports/blob/master/7/debian-10/rootfs/opt/bitnami/scripts/jasperreports/entrypoint.sh#L24
- https://github.com/bitnami/bitnami-docker-jasperreports/blob/master/7/debian-10/rootfs/post-init.sh
