### ISSUE TITLE
jasperserver webapps dir persisting?

### ISSUE THREAD

**Issue by dosfx** [bitnami/bitnami-docker-jasperreports#111]
This may be a dumb question and I'm totally down the wrong path, asking for patience:

We follow the advice in the readme and mount in an extra volume to the jasperreports container for, my understanding, persisting the application's extracted war in the tomcat webapps dir so that 1. startup goes faster without a full installation every time its a re-created container and 2. configuration edits will persist.

As a shortcut in order to "edit" files in the /bitnami persistence volume we simply mounted them in as well with docker set as read only so as not to get changed and that all seemed to work. WAS `/bitnami/tomcat/data/jasperserver/...` NOW `/bitnami/tomcat/webapps/jasperserver/...`

With the latest version the path has changed within the /bitnami volume. I updated our edited files mount paths. The image does not boot complaining

```
staging.ast.jasper       | jasperreports 15:08:15.96 
staging.ast.jasper       | jasperreports 15:08:15.96 Welcome to the Bitnami jasperreports container
staging.ast.jasper       | jasperreports 15:08:15.96 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jasperreports
staging.ast.jasper       | jasperreports 15:08:15.97 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jasperreports/issues
staging.ast.jasper       | jasperreports 15:08:15.97 
staging.ast.jasper       | jasperreports 15:08:15.98 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
staging.ast.jasper       | jasperreports 15:08:16.01 INFO  ==> Configuring port numbers
staging.ast.jasper       | jasperreports 15:08:16.02 INFO  ==> Persisted webapps detected
staging.ast.jasper       | jasperreports 15:08:16.06 INFO  ==> Restoring persisted JasperReports installation
staging.ast.jasper       | jasperreports 15:08:16.10 INFO  ==> Trying to connect to the database server
staging.ast.jasper       | jasperreports 15:08:16.15 INFO  ==> Executing upgrade scripts
staging.ast.jasper       | jasperreports 15:08:16.15 INFO  ==> Running upgrade script
staging.ast.jasper       | /opt/bitnami/scripts/libjasperreports.sh: line 309: /opt/bitnami/jasperreports/WEB-INF/classes/resfactory.properties: No such file or directory
```

Trying to investigate, I noticed that inside the /bitnami volume there is a symlink outside of the volume to /opt/bitnami for the jasperserver webapps directory:

```I have no name!@879e9ea72148:/$ ls -l /bitnami/tomcat/webapps/
total 4
drwxrwxr-x  3 1001 root  223 Jan 10 16:19 ROOT
drwxrwxr-x 15 1001 root 4096 Jan 10 16:19 docs
drwxrwxr-x  7 1001 root   99 Jan 10 16:19 examples
drwxrwxr-x  6 1001 root   79 Jan 10 16:19 host-manager
lrwxrwxrwx  1 1001 root   26 Jan 18 14:58 jasperserver -> /opt/bitnami/jasperreports
drwxrwxr-x  6 1001 root  114 Jan 10 16:19 manager
```

 Is this correct? Unless I'm mistaken, I would think that would break the whole idea of persisting the jasper application directory since it links outside the volume.

If I remove the volumed in "edit" files the server starts just fine. So I assume the issue is something to do with the files overwriting the symlink in the volume and just messing with everything. So the real question here is how to persist edits to configuration files in jasperserver.

**Comment by dosfx** [comment]
I should say if I remove the mounted in "edited" files from the compose file the server boots up just fine.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-jasperreports#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
