### ISSUE TITLE
README.md Example SMTP settings for gmail don't work

### ISSUE THREAD

**Issue by cro1y** [bitnami/bitnami-docker-jasperreports#112]
**Description**
The instructions in the README.md to configure SMTP for Gmail cause an exception.

If you modify the docker-compose.yml as per the "SMTP configuration using a Gmail account"  (using valid gmail account details obviously!), the server will throw an exception when it attempts to email.

**Steps to reproduce the issue:**
1. as per the README.md, edit the docker-compose.yml and add the SMTP specific env variables
      - JASPERREPORTS_SMTP_HOST=smtp.gmail.com
      - JASPERREPORTS_SMTP_PORT_NUMBER=587
      - JASPERREPORTS_SMTP_USER=your_email@gmail.com
      - JASPERREPORTS_SMTP_PASSWORD=your_password
2. schedule a report and email the results.
3. an exception will be thrown that 
ERROR ReportExecutionJob,quartzScheduler_Worker-1:367 - The job error notification was not completed. An error occurred while sending it. (Error UID: f79266f7-e559-4e53-86fb-da805d9908e6) org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.NoSuchProviderException: **Invalid protocol: null. Failed messages:** javax.mail.NoSuchProviderException: Invalid protocol: null; message exception details (1) are:
jasperreports_1  | Failed message 1:
jasperreports_1  | **javax.mail.NoSuchProviderException: Invalid protocol: null**

**Describe the results you expected:**

No exception and an email via the defined Gmail account should be sent.

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**
If you do add a protocol definition, e.g. - JASPERREPORTS_SMTP_PROTOCOL=
The two options allowed by the scripts are ssl or tls and both of these will return a exception
 javax.mail.NoSuchProviderException: No provider for ssl  [or tls as appropriate).

**Comment by juan131** [comment]
Hi @cro1y 

Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-jasperreports#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by cro1y** [comment]
I tried all combinations of JASPERREPORTS_SMTP_PROTOCOL but to no avail.

This issue seems to come down to the _report.scheduler.mail.sender.protocol_ value injected into **js.quartz.properties**

Currently the value of JASPERREPORTS_SMTP_PROTOCOL is injected and valid values for this are blank, tls or ssl. None of which are actual valid protocol values for javax.mail

What does work is a value of **smtp** – or at least it will work then!

I removed the tls/ssl validation in the scripts for JASPERREPORTS_SMTP_PROTOCOL as passed smtp and then it does email.

I haven’t supplied a patch because this validation of the JASPERREPORTS_SMTP_PROTOCOL seems very explicit so I see my change as a simple hack not a real fix.  Surely there is a purpose to enforcing of either tls or ssl … I just don't know the code well enough to determine it!?

I also tested with smtp.office365.com – this change works here too but Microsoft are moving to enforce TLS1.2 as a minimum secure connection protocol so I found when I modified libjasperreports.sh to explicitly define this in applicationContext-report-scheduling.xml it worked flawlessly.

```
if ! is_empty_value "$JASPERREPORTS_SMTP_HOST"; then
    # Fix that needs to be done after the installation on SMTP
    # Source: https://github.com/bitnami/bitnami-docker-jasperreports/issues/49
    # We need to use * in the XPath expressions because it is a namespaced XML but the namespace is not properly detected
    # in regular XPath experssions with namespace
    # Set mail.smtp.auth to true
     xmlstarlet ed -L -u '//*[name()="prop" and @key="mail.smtp.auth"]' -v "true" "${JASPERREPORTS_BASE_DIR}/WEB-INF/applicationContext-report-scheduling.xml"
     # Add a new prop node with mail.smtp.startls.enable=true
     xmlstarlet ed -L --subnode '//*[name()="property" and @name="javaMailProperties"]/*[name()="props"]' --type elem -n "prop" -v "true" "${JASPERREPORTS_BASE_DIR}/WEB-INF/applicationContext-report-scheduling.xml"
     xmlstarlet ed -L -i '//*[name()="prop" and not(@key)]' --type "attr" -n "key" -v "mail.smtp.starttls.enable" "${JASPERREPORTS_BASE_DIR}/WEB-INF/applicationContext-report-scheduling.xml"
     # add a new prop node with mail.smtp.ssl.protocols=TLSv1.2
     xmlstarlet ed -L --subnode '//*[name()="property" and @name="javaMailProperties"]/*[name()="props"]' --type elem -n "prop" -v "TLSv1.2" "${JASPERREPORTS_BASE_DIR}/WEB-INF/applicationContext-report-scheduling.xml"
     xmlstarlet ed -L -i '//*[name()="prop" and not(@key)]' --type "attr" -n "key" -v "mail.smtp.ssl.protocols" "${JASPERREPORTS_BASE_DIR}/WEB-INF/applicationContext-report-scheduling.xml"
fi

```
As I made these changes I wondered, was this the original idea behind the tls/ssl values for JASPERREPORTS_SMTP_PROTOCOL ?  Was it intended as a value to be injected into mail.smtp.ssl.protocols rather than  report.scheduler.mail.sender.protocol ?

With these changes the resulting js.quartz.properties looks like
GMAIL/Office365
```
report.scheduler.mail.sender.host= smtp.gmail.com/smtp.office365.com
report.scheduler.mail.sender.username=gmailUser/office365User
report.scheduler.mail.sender.password=gmailUserPassword/office365Password
report.scheduler.mail.sender.from=gmailUser/office365User
report.scheduler.mail.sender.protocol=smtp
report.scheduler.mail.sender.port=587
```

and applicationContext-report-scheduling.xml in both instances 
```
 <bean id="reportSchedulerMailSender" class="org.springframework.mail.javamail.JavaMailSenderImpl">
        <property name="host" value="${report.scheduler.mail.sender.host}"/>
        <property name="username" value="${report.scheduler.mail.sender.username}"/>
        <property name="password" value="${report.scheduler.mail.sender.password }"/>
        <property name="protocol" value="${report.scheduler.mail.sender.protocol}"/>
        <property name="port" value="${report.scheduler.mail.sender.port}"/>
        <property name="javaMailProperties">
            <props>
                <!--prop key="mail.smtps.ssl.enable">false</prop-->
                <prop key="mail.smtp.auth">true</prop>
                <prop key="mail.smtp.starttls.enable">true</prop>
                <prop key="mail.smtp.ssl.protocols">TLSv1.2</prop>
                <prop key="mail.debug">true</prop>
            </props>
        </property>
    </bean>
```

And then it emails without issues - it's not a patch but perhaps it will help someone else struggling with this.
