### ISSUE TITLE
Postgresql Support

### ISSUE THREAD

**Issue by sam-cgr** [bitnami/bitnami-docker-jasperreports#118]
This would be really useful

_Originally posted by @sam-cgr in https://github.com/bitnami/bitnami-docker-jasperreports/issues/63#issuecomment-1103416704_

**Comment by sam-cgr** [comment]
Hi, I gave it a crack to implement it - it will likely need a lot of work. I am not very familiar with bash.

**Comment by carrodher** [comment]
Thanks for creating the PR, we will evaluate it and provide feedback
