### ISSUE TITLE
docker-compose not working if ALLOW_EMPTY_PASSWORD=NO

### ISSUE THREAD

**Issue by nani2ratna** [bitnami/bitnami-docker-jasperreports#122]
### Name and Version

bitnami/jasperreport

### What steps will reproduce the bug?

Downloaded docker-compose file - https://github.com/bitnami/bitnami-docker-jasperreports/blob/master/docker-compose.yml
When execute this docker-compose as it is then it spins up mariadb and jasperreports. 
But when removed `- ALLOW_EMPTY_PASSWORD=yes` from environment from both mariadb and jasperrports service. And then added `MARIADB_PASSWORD=bn_jasperreports` to mariadb service and `JASPERREPORTS_DATABASE_PASSWORD=bn_jasperreports` jasperreport service so I can carry on deploy into our stack, but jasperreports container is not able to connect to mariadb. Should we change sql scripts to get jasperreports connected to maridb ? 

### What is the expected behavior?

jasperreports container should be connect

### What do you see instead?

jaspererports not connecting to mariadb and exit with below message
`jasperreports_1  | jasperreports 02:52:28.38 ERROR ==> Could not connect to the database
`

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-jasperreports#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
