### ISSUE TITLE
Postgres fails to connect

### ISSUE THREAD

**Issue by yoda** [bitnami/bitnami-docker-jasperreports#123]
### Name and Version

bitnami/bitnami-docker-jasperreports

### What steps will reproduce the bug?

Using the postgres configuration try to use the postgres database

### What is the expected behavior?

It should work

### What do you see instead?

The connection fails due to missing files and libraries.

**Comment by javsalgar** [comment]
Hi!

Please, note this solution is community-supported. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version.
