### ISSUE TITLE
Seeing "mkdir: cannot create directory '/bitnami/jasperreports/buildomatic/conf_source/db/postgresql': Permission denied" when using latest image

### ISSUE THREAD

**Issue by ujo-trackunit** [bitnami/bitnami-docker-jasperreports#124]
### Name and Version

bitnami/jasperreports:8.0.0

### What steps will reproduce the bug?

1. Have image before PostgreSQL/non-root support with attached folder on `/bitnami/jasperreports`.
2. Upgrade to newest with PostgreSQL support

Seeing the following in the logs when start tries to start:

```
jasperreports 08:49:39.16 
jasperreports 08:49:39.16 Welcome to the Bitnami jasperreports container
jasperreports 08:49:39.16 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jasperreports
jasperreports 08:49:39.16 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jasperreports/issues
jasperreports 08:49:39.16 
jasperreports 08:49:39.17 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
jasperreports 08:49:39.18 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
jasperreports 08:49:39.21 INFO  ==> Configuring port numbers
jasperreports 08:49:39.22 INFO  ==> Ensuring Tomcat directories exist
jasperreports 08:49:39.22 INFO  ==> Deploying Tomcat from scratch
jasperreports 08:49:39.31 WARN  ==> Could not find required file /bitnami/jasperreports/buildomatic/conf_source/db/postgresql/db.template.properties, it will be created
mkdir: cannot create directory '/bitnami/jasperreports/buildomatic/conf_source/db/postgresql': Permission denied
```

We are doing customer stuff with the image - but it seem to be related to the image running as USER 1001, and folder is owned by root 

```
I have no name!@jasperreports-7547f8678c-ksfh7:/$ ls -la /bitnami/jasperreports/buildomatic/conf_source/db           
total 12
drwxr-xr-x 3 root root 6144 Dec 18  2020 .
drwxr-xr-x 3 root root 6144 Dec 18  2020 ..
drwxr-xr-x 2 root root 6144 Dec 18  2020 mysql
```

We might have started using the image when USER was root. It there a simple workaround?

### What is the expected behavior?

Image starts without error.

### What do you see instead?

Error creating folder. Application does not start.

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-jasperreports#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by ujo-trackunit** [comment]
Executed the following as root in another pod attached to the same volume:

```
/bitnami/jasperreports # chown -R 1001:root *
```

**Comment by ujo-trackunit** [comment]
Seeing that mentioned in the docs:

> As a consequence, the data directory must be writable by that user. You can revert this behavior by changing USER 1001 to USER root in the Dockerfile.

So I will close this issue.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing your workaround.
