### ISSUE TITLE
running jasperserver behind a preexisting jwilder/nginx-proxy container

### ISSUE THREAD

**Issue by jpstaub** [bitnami/bitnami-docker-jasperreports#37]
-------------------------------
    COMPATIBILITY ISSUES
-------------------------------
**Description**
The primary challenges encountered when running JasperServer behind a preexisting [jwilder/nginx-proxy ](https://github.com/jwilder/nginx-proxy) container were:

1. Connecting the preexisting jwilder/nginx-proxy container to the JasperServer network set up by the docker-compose process.
2. Adjusting the jwilder/nginx-proxy container to accommodate the pass through of underlines. 
  
**Resolution for Compatibility Issue 1**

The docker-compose file was implemented normally then the preexisting jwilder/nginx-proxy container was added to the resulting docker-compose generated network via the following:

```
$ docker network ls
$ docker network connect [network] [preexisting jwilder/nginx-proxy container name]
$ docker network inspect [network]
```

**Resolution for Compatibility Issue 2**

Out of the box, nginx proxy is not compatible with JasperServer because JasperServer makes use of [OWASP CSRFGuard](https://www.owasp.org/index.php/Category:OWASP_CSRFGuard_Project) which requires [underscores in headers](http://uber-root.io/uber-roots-ql-stuff/nginx-and-owasp-csrfguard#comment). [Underscores are turned off](http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers)  by default in nginx.

The location of the nginx file which requires modification (this requires a /bin/bash into the container):
`/etc/nginx/nginx.conf`

The required modification syntax:
` underscores_in_headers on;`

The modified file should look like:
```
http {
    server_names_hash_bucket_size 128;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    underscores_in_headers on;
}
```

**Version**

- Output of `docker info`:

```
Containers: 27
 Running: 17
 Paused: 0
 Stopped: 10
Images: 29
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 405
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.78 GiB
Name: ripcord-services
ID: RA6I:YRKW:AVVE:3KPK:7LVK:K2CQ:G7IG:4FQQ:CMTG:FRZU:JDIL:CET6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
```

- Output of `docker version`:

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by silviofdez** [comment]
Could you please detail what changes or issues are you referring in our container?

**Comment by jpstaub** [comment]
Your container is fine. The intent here is to leave breadcrumbs behind for others that may be experiencing the similar problems when using your container in a more production oriented environment.

Regards,
Jake

**Comment by silviofdez** [comment]
Thanks so much for your contribution.
