### ISSUE TITLE
Missing features?

### ISSUE THREAD

**Issue by eczajk1** [bitnami/bitnami-docker-jasperreports#45]
**Description**

I am brand new to JasperReports. What I don't understand is why this interface seems to be quite different from what is described in JasperReports [documentation](http://community.jaspersoft.com/documentation/tibco-jasperreports-server-user-guide/v640/introduction-jasperreports-server).

Is this a bug or am I missing something? I would really appreciate any information here. Thanks in advance.

**Steps to reproduce the issue:**

1. Installed the application as shown at https://github.com/bitnami/bitnami-docker-jasperreports#run-the-application-manually
2. Logged into the browser application.
3. (This part worked fine.)

**Describe the results you received:**

This much worked fine for me.

**Describe the results you expected:**

For examples, the Getting Started page that I see has none of the graphics and "quick access" links that are shown in [the documentation](http://community.jaspersoft.com/documentation/tibco-jasperreports-server-user-guide/v640/getting-started-page). In fact, the only thing I see that shows "Getting Started" is on the main login screen (`/jasperserver/login.html`).

Once I've logged in, I do not see the "Create" Menu item at all.

**Additional information you deem important (e.g. issue happens only occasionally):**

Screenshots:

![image](https://user-images.githubusercontent.com/2584923/30496864-bd56c34a-9a1e-11e7-97e5-0493d1320d57.png)

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.38-16.35.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.03
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: ip-172-31-3-210
ID: IQEF:ZFA5:SQZC:34YQ:7Z64:UNOD:OZ3T:GB3T:VJP6:YDWN:GEEA:RBBM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Thanks for reporting. If you go to the rest of the sections, you will see that the UI is quite similar. Only the theme is slightly different and I think it is because the documentation can be applied to both JasperReports Community and Pro. Because of this, I think that this getting started page (and the slight theme differences) is available only in JasperReports Pro.

**Comment by javsalgar** [comment]
@sra I added a datasource by rightclicking in one of the folders on the left pane. Add Resource -> Datasource
