### ISSUE TITLE
New container (Jasperreport Server 7.1.0) doesn't start after updating container

### ISSUE THREAD

**Issue by alois74** [bitnami/bitnami-docker-jasperreports#50]
**Description**

4 weeks ago, I updated my container (Jasperreport Server 6.4.3 Build 20180326_2258). 
After upgrading container to new version (Jasperreport Server 7.1.0), the container doesn't start correctly. When I try to access the Jasperreport Server from my browser, I get redirected to <servername>:8080/jasperserver/ and then I get an Apache Tomcat Error, that this resource isn't known.

Is Jasperreport docker container not updateable from 6.4.3 to 7.1.0 or did I miss anything?

Any help appreciated.

**Steps to reproduce the issue:**

1. docker stop jasperreports
2. docker pull bitnami/jasperreports:latest
3. docker rm jasperreports
4. docker run --name jasperreports bitnami/jasperreports:latest

Container is running, apache tomcat starts, but after redirect to /jasperserver I get a resource unknown error from tomcat. It seems that the tomcat server doesn't correctly deploy the application.

**Comment by juan131** [comment]
Hi @alois74 

I was able to reproduce the issue. I used a different approach (using **docker-compose.yaml**) but it's exactly the same:

```
wget https://raw.githubusercontent.com/bitnami/bitnami-docker-jasperreports/master/docker-compose.yml
sed -i -e 's/jasperreports:latest/jasperreports:6.4.3-r0/g' docker-compose.yml
docker-compose up -d
sed -i -e 's/jasperreports:6.4.3-r0/jasperreports:latest/g' docker-compose.yml
docker-compose pull
docker-compose up -d --no-deps --build jasperreports
```

When upgrading to a major version this kind of "easy" upgrades usually don't work. It's easy to replace one Docker Image by the new one when upgrading between minor versions but it's very likely to find these errors in cases like yours.

I know it's a pain, but I guess the solution in your case would be to follow the official upgrade process:
https://community.jaspersoft.com/documentation/tibco-jasperreports-server-community-project-upgrade-guide/v71/upgrading-64-71-0

**Comment by alois74** [comment]
Hi @juan131

Thank you for your reply. I wasn't sure how to do the update inside the container, so I tried to 
1. exported the actual config of the old jasperreports server 
    from inside JasperReports Server under "Manage" -> "Server configuration" -> "Export"
2. stopped the containers (jasperreports server and mariadb)
3. backed up the persistent directories (jasperreports server and mariadb)
4. cleaned the persistent directories (rm -r /path/to/volume)
5. deployed new (now empty containers) with the new version of jasperreports server
6. imported the old configuration inside the new JasperReports Server
    "Manage" -> "Server configuration" -> "Import"

At least in my case this worked :-)

**Comment by juan131** [comment]
Thanks for sharing the solution!!! I am sure it will be very useful for other users migrating from older versions!
