### ISSUE TITLE
Kubernets chart: PersistentVolumeClaim is not bound

### ISSUE THREAD

**Issue by kevinblanco** [bitnami/bitnami-docker-jasperreports#51]
**Description**

Command executed: `helm install --name jaspersoft stable/jasperreports` 

After executing a new charm on my kubernets cluster, I get errors on the instantiation, the "jasper-jasperreports" and "jasper-mariadb" pods have the following error: 

`PersistentVolumeClaim is not bound: "jaspersoft-jasperreports"` and `PersistentVolumeClaim is not bound: "jaspersoft-mariadb"`. 

Looking at the `PersistentVolumeClaim`s created I see both are on PENDING state, but doesn't have any error, any log, describing the pvc doesn't show any hint. 

I tried a second helm install adding the property `persistence.storageClass` to `standard` or a lower `persistence.size` but it didn't make any difference 

**Steps to reproduce the issue:**

1. helm install --name jaspersoft stable/jasperreports
2. See Cluster Overview
3. Notice errors on the pods binding to the PersistentVolumeClaim

**Kubernets version**

Version: v1.8.11-2+fa6873d3e386d7

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.13-2+e478967b11e322", GitCommit:"e478967b11e322acd2409fe17246bca5b5bc80c1", GitTreeState:"clean", BuildDate:"2018-06-14T02:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tompizmor** [comment]
I just tried the same command and it worked for me. Could you please run these commands and paste here the output?

```
$ kubectl describe pvc jaspersoft-jasperreports
$ kubectl describe pvc jaspersoft-mariadb
```
