### ISSUE TITLE
Custom configuration

### ISSUE THREAD

**Issue by maclonghorn** [bitnami/bitnami-docker-jasperreports#52]
Not a bug, but a question:
I'd like to add a JNDI source.  I've read on the Tibco site how to do this and it works great.  What this involves though is updating two config files:
- `/opt/bitnami/jasperreports/META-INF/context.xml`
- `/opt/bitnami/jasperreports/WEB-INF/web.xml`

What's the best way to accomplish this?

**Comment by maclonghorn** [comment]
That would work great for local development but for deployment on AWS I'm
not going to have a local drive too mount.

**Comment by javsalgar** [comment]
In environments like Kubernetes, you would use elements like ConfigMaps for example. Do you plan to use simply docker in your production environment?

**Comment by maclonghorn** [comment]
Rancher, Docker, and AWS.

**Comment by javsalgar** [comment]
If you are using Rancher, ConfigMaps seem to be available as well: https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/configmaps/

**Comment by javsalgar** [comment]
Hi,

I do not know much about Cattle. I see that something similar to configmaps is being requested.

https://github.com/rancher/rancher/issues/9218
