### ISSUE TITLE
Website does not load outside of local deployment.

### ISSUE THREAD

**Issue by bluesquid12** [bitnami/bitnami-docker-jasperreports#62]
**Description**
When I run a `docker-compose up` it brings everything up and it looks as if its working. When I try to open the page from a web browser it just waits at ip:8080/ then it redirects to ip:8080/jasperserver but then it just stops there. It does not even get a status code for ip:8080/jasperserver. Is there a timeout or some other parameter set that could be doing this? I have done the exact same deployment on my local machine in docker and it works fine.
<img width="960" alt="slow_page" src="https://user-images.githubusercontent.com/49572752/56067523-ab008300-5d38-11e9-9242-66e97fa95ccc.png">

**Comment by javsalgar** [comment]
Hi,

Could you let us know more information about your target platform? Where are you deploying the installation? Does it have any firewall settings?

**Comment by bluesquid12** [comment]
This was a networking problem not jasper.
