### ISSUE TITLE
Unknown SMTP host: mail.example.com

### ISSUE THREAD

**Issue by munkiepus** [bitnami/bitnami-docker-jasperreports#64]
**Description**

After setting up the smtp environment variables and trying to run a scheduled report with email notifications i'm seeing: 

          Unknown SMTP host: mail.example.com;

using another docker container to view the emails, mailcatcher

**Steps to reproduce the issue:**

          - SMTP_HOST=mailcatcher
          - SMTP_PORT=1025
          - SMTP_EMAIL=email@domain.com

create a scheduled report with notifications and run the report

**Describe the results you received:**

no mail is sent and this is sseeen in the logs:
javax.mail.MessagingException: Unknown SMTP host: mail.example.com;
jasper_reports       |   nested exception is:
jasper_reports       |  java.net.UnknownHostException: mail.example.com. Failed messages: javax.mail.MessagingException: Unknown SMTP host: mail.example.com;
jasper_reports       |   nested exception is:
jasper_reports       |  java.net.UnknownHostException: mail.example.com; message exception details (1) are:
jasper_reports       | Failed message 1:
jasper_reports       | javax.mail.MessagingException: Unknown SMTP host: mail.example.com;
jasper_reports       |   nested exception is:
jasper_reports       |  java.net.UnknownHostException: mail.example.com
jasper_reports       |  at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1280)
jasper_reports       |  at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:370)
jasper_reports       |  at javax.mail.Service.connect(Service.java:275)
jasper_reports       |  at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:503)
jasper_reports       |  at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:422)
jasper_reports       |  at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:346)
jasper_reports       |  at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:341)
jasper_reports       |  at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJobMailNotificationImpl.sendMailNotification(ReportExecutionJobMailNotificationImpl.java:141)
jasper_reports       |  at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.sendMailNotification(ReportExecutionJob.java:1123)
jasper_reports       |  at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.executeAndSendReport(ReportExecutionJob.java:581)
jasper_reports       |  at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.execute(ReportExecutionJob.java:248)
jasper_reports       |  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
jasper_reports       |  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
jasper_reports       | Caused by: java.net.UnknownHostException: mail.example.com
jasper_reports       |  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
jasper_reports       |  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
jasper_reports       |  at java.net.Socket.connect(Socket.java:589)
jasper_reports       |  at java.net.Socket.connect(Socket.java:538)
jasper_reports       |  at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:232)
jasper_reports       |  at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:189)
jasper_reports       |  at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1250)
jasper_reports       |  ... 12 more

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 18.09.2, build 6247962
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown

```

**Comment by munkiepus** [comment]
on closer inspection, it looks like it's defined in ./opt/bitnami/tomcat/webapps/jasperserver/WEB-INF/js.quartz.properties

**Comment by alemorcuq** [comment]
Hi, @munkiepus.

How are you deploying your containers? Could you share more information on that?

The `SMTP_XXXX` environment variables get written to the file `/opt/bitnami/jasperreports/buildomatic/default_master.properties`:

```
quartz.mail.sender.host=mailcatcher
quartz.mail.sender.port=1025
quartz.mail.sender.protocol=smtp
quartz.mail.sender.username=your_email@gmail.com
quartz.mail.sender.password=your_password
quartz.mail.sender.from=email@domain.com
```

Then, when JasperReports gets deployed, they are written to the file `/opt/bitnami/jasperreports/WEB-INF/js.quartz.properties`:

```
report.scheduler.mail.sender.host=mailcatcher
report.scheduler.mail.sender.username=your_email@gmail.com
report.scheduler.mail.sender.password=your_password
report.scheduler.mail.sender.from=email@domain.com
report.scheduler.mail.sender.protocol=smtp
report.scheduler.mail.sender.port=1025
```

Can you check the contents of those files and see if you see the correct values there?

Regards,
Alejandro

**Comment by munkiepus** [comment]
Deploying with docker compose
```    jasperreports:
        container_name: jasper_reports
        image: 'bitnami/jasperreports:latest'
        environment:
          - MARIADB_HOST=jasper_mariadb
          - MARIADB_PORT_NUMBER=3306
          - JASPERREPORTS_DATABASE_USER=bn_jasperreports
          - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
          - ALLOW_EMPTY_PASSWORD=yes
          - JASPERREPORTS_EMAIL=developers@domain.org
          - SMTP_HOST=mailcatcher
          - SMTP_PORT=1025
          - SMTP_EMAIL=developers@domain.org
        labels:
          kompose.service.type: nodeport
        expose:
          - '8080'
          - '8443'
        ports:
          - '8080:8080'
        volumes:
          - 'jasperreports_data:/bitnami'

        depends_on:
          - mariadb_jasper
        networks:
          - stack

    mariadb_jasper:
        container_name: jasper_mariadb
        image: 'bitnami/mariadb:latest'
        environment:
          - MARIADB_USER=bn_jasperreports
          - MARIADB_DATABASE=bitnami_jasperreports
          - ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - 'mariadb_data:/bitnami'
        networks:
          - stack
```

**Comment by alemorcuq** [comment]
Hi, @munkiepus.

Do you already have data in the jasperreports volume by any chance? I'm asking because that `docker-compose.yml` should fail due to missing SMTP environment variables, so to me it looks like JasperReports it's not getting initialized but it's restoring data from a previous deployment. 

Can you share the `docker-compose` logs?

Regards,
Alejandro

**Comment by munkiepus** [comment]
Ah yes i have a persistent volume for this, i suspect the relevant bit in the DC logs is this:

```
jasper_reports       | tomcat  INFO  ########################################################################
jasper_reports       | tomcat  INFO   Installation parameters for tomcat:
jasper_reports       | tomcat  INFO     Persisted data and properties have been restored.
jasper_reports       | tomcat  INFO     Any input specified will not take effect.
jasper_reports       | tomcat  INFO   This installation requires no credentials.
jasper_reports       | tomcat  INFO  ########################################################################
```

That was indeed the problem, having removed the volume that it now picks up the correct params.

Thnaks
