### ISSUE TITLE
Oracle JDBC Driver 

### ISSUE THREAD

**Issue by SudharsanN** [bitnami/bitnami-docker-jasperreports#66]
I am setting up the JasperReports on our DEV environment and one of the requirement is to connect to in-house Oracle database. Since the Oracle JDBC driver is not available by default, I installed the same by uploading the ojdbc8.jar and I am able to connect to the Oracle database and generate reports. 

My questions are:
1) Is this jar stored on the file system somewhere? I logged into the running container and searched for it but couldn't locate it. Is this jar stored in the database?
2) According to Jasper Reports documentation, the jar should be placed at <js-install>/buildomatic/conf_source/db/oracle/native.jdbc but I didn't place it there nor updated the default_master.properties file. But still everything was working fine.
3) How can I make the JDBC driver available across the other environments like QA, PROD without manually adding the driver from the UI ?

Do let me know if you need any more information.

**Comment by rafariossaa** [comment]
Hi @SudharsanN,

  I would like to reproduce this, could you give me instructions on how to install the ojdbc8.jar ?

thanks forehand.

**Comment by SudharsanN** [comment]
Hi @rafariossaa,
In the server UI, I selected the option to add DataSource and that brings up the screen to select the drivers related to database. The drivers for Postgres and MySql are already part of the JasperServer. So, when I selected the option of Oracle (oracle.jdbc.OracleDriver), the button "Add Driver" appears and on clicking of that, we are asked to upload the corresponding JAR for it. 

Details instructions are available at https://community.jaspersoft.com/documentation/jasperreports-server-administration-guide/v561/managing-jdbc-drivers under section "To Add a JDBC Driver".

**Comment by SudharsanN** [comment]
@rafariossaa Were you able to reproduce the issue? Do you need any info from me ?

**Comment by rafariossaa** [comment]
Hi @SudharsanN,
  1) I was able to find the file in /opt/bitnami/tomcat/temp directory, but it has a name like: `jdbc-1569225380249-553751.jar`.
  2) I couldn't find it in that place, maybe you could ask in jasperreport's forums.
  3) For this, what you can do is create a image of the container once you have all you need installed.(docker commit)

**Comment by rafariossaa** [comment]
Hi @SudharsanN ,
  Did you tried what I indicated ?

**Comment by SudharsanN** [comment]
@rafariossaa  I couldn't get it working as you indicated. Do you have a sample of some sort that I can refer to ?

**Comment by rafariossaa** [comment]
@SudharsanN , I mean using this:

https://docs.docker.com/engine/reference/commandline/commit/#extended-description
