### ISSUE TITLE
SQL Server Database

### ISSUE THREAD

**Issue by danielfcastro** [bitnami/bitnami-docker-jasperreports#67]
Is it possible to use SQL Server Database rather than MariaDb?  If so, what are the environment variables names to be used and how to configure the driver?

**Comment by carrodher** [comment]
Hi, out-of-the-box the jasperreports container is oriented to be used with MariaDB/MySQL using the environment variables as described in [this section of the README](https://github.com/bitnami/bitnami-docker-jasperreports#environment-variables), both, creating a database via mysql-client or using an existing one.
About SQL Server: We didn't test this database in any of our containers.
