### ISSUE TITLE
Edit JasperServer Specific Config Files

### ISSUE THREAD

**Issue by SudharsanN** [bitnami/bitnami-docker-jasperreports#68]
I am trying to save the reports generated by the user from JasperServer to the host machine. In order to do that, I have to change the value of property "enableSaveToHostFS" to "true" in the file /opt/bitnami/jasperreports/WEB-INF/applicationContext.xml . Though, I login to the running container and change the value, it won't take effect unless I restart the server. Which I am not sure how to do. Can you clarify on the below ?

1. How to restart the server so that the changes take into effect?
2. Is it possible to change the file content by mounting an external file from the host during docker run ? 
3. What is the preferred way to go about config file changes as JasperServer is heavily configuration driven?

Thanks,
Sudharsan N.

**Comment by miguelaeh** [comment]
Hi @SudharsanN ,
How did you deploy the server? 
In case you used `docker-compose` you can try with `docker-compose restart`.
Have in mind that the reports will be stored into the container not in your host, but you can try mounting a volume where to store the reports.

> Is it possible to change the file content by mounting an external file from the host during docker run ?
At this moment this is not possible. It is something that we probably should support.

**Comment by SudharsanN** [comment]
Hi @miguelaeh,
I am using docker run command to get the container running so not sure of how to restart the tomcat.

As far as mounting file is concerned, I tried it in the run command by specifying the -v argument but the changes in the host file didn't get reflect. Rather, my host file for changed with the contents from the image. 

Without the ability to edit and reload configuration, its difficult to use the image.

**Comment by miguelaeh** [comment]
Hi @SudharsanN ,
To restart a container with `docker` command use `docker restart <container-ID>` where the container id is the returned by `docker ps` command.

I have tried mounting a volume and it seems it is not possible, by the moment you can modify it manually and using `docker restart <ID>`. I am going to create an internal task to allow mounting a custom configuration file.

**Comment by sarawutsangaroon** [comment]
Do we have any progress of this issue ?
I really want to know how to make change and effective after container restarted.
I want to modify crosstab limitation at /opt/bitnami/jassperreports/WEB-INF/classes/jasperreports.properties

For my case, I run the Jasper in K8S.

**Comment by miguelaeh** [comment]
Hi @sarawutsangaroon ,
I am afraid we had not the chance to work on this yet.
We will update this thread when we have news.

**Comment by buddemat** [comment]
> I really want to know how to make change and effective after container restarted.

For me, the workaround from @huang-tianwen in issue #73 did it (https://github.com/bitnami/bitnami-docker-jasperreports/issues/73#issuecomment-617039641). 

I just put a bunch of sed commands that change some of the configuration files as I need it just before the fi in /rootfs/app-entrypoint.sh. When I deploy the container, the config is just the way I want it right from the start.

**Comment by miguelaeh** [comment]
Hi @buddemat ,
Thank you very much for sharing your workaround. Sadly, we are a small team and we had not the time to work on this yet.
Sorry for the inconvenience.

**Comment by guaychou** [comment]
Hi added a pull request to fix this issue, can you help to review ? @miguelaeh

**Comment by miguelaeh** [comment]
Hi @guaychou ,
We are already taking care of it

**Comment by nisrael** [comment]
I think this is already possible with the current version. Just add a bind to a script, which copies the files.
There is a small drawback though: it is not working on windows because the executable flag of the script has to be set on the host filesystem.

docker-compose.yml
```
[...]
volumes:
      - ./jasperreports/persistence:/bitnami/jasperreports
      - ./jasperreports/config:/etc/opt/bitnami/jasperreports/config
      - type: bind
        source: ./custom_config.sh
        target: /docker-entrypoint-init.d/custom_config.sh
```

custom_config.sh
```
#!/bin/bash
#
if [ -d "/etc/opt/bitnami/jasperreports/config/" ]; then
    echo "Copying custom_config"
    if ! [ -z "$(ls -A /etc/opt/bitnami/jasperreports/config/)" ]; then
        cp -v -r "/etc/opt/bitnami/jasperreports/config/"* "/opt/bitnami/jasperreports/WEB-INF/"
    fi
fi
```
