### ISSUE TITLE
JasperReports doesn't launch on EC2 instance

### ISSUE THREAD

**Issue by SudharsanN** [bitnami/bitnami-docker-jasperreports#69]
Hi,
We are deploying JasperReport on an EC2 instance of type t2 medium whose configuration is "Variable ECUs, 2 vCPUs, 2.3 GHz, Intel Broadwell E5-2686v4, 4 GiB memory". During the creation of docker container with bitnami/jasperreports:7 image, we are seeing the below error in the container logs.

Error executing 'postInstallation': [exec] Execute failed: java.io.IOException: Cannot run program "git": error=2, No such file or directory.
BUILD FAILED
/opt/bitnami/jasperreports/buildomatic/bin/import-export.xml:321: The following error occurred while executing this line:/opt/bitnami/jasperreports/buildomatic/bin/import-export.xml:199: Java returned: 137
Total time: 4 minutes 14 seconds

We have no idea on what this error is as we haven't encountered any such errors on local machine. Can you please look into this issue on priority ?

**Comment by andresbono** [comment]
Hi @SudharsanN:

- Can you share the specific `docker` command that you are executing on your EC2 instance?
- Can you execute `docker version` and share the output with us?
- Can you share the AMI id of the EC2 instance you are using? In case that it's a public AMI.

**Comment by SudharsanN** [comment]
Hi @andresbono 
Please see my response below.

- We are deploying it as ECS with EC2 as the ecs instance. So, all we have is container definition. 

- docker version is as below
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Fri Jun 28 23:16:08 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Fri Jun 28 23:17:39 2019
  OS/Arch:          linux/amd64
  Experimental:     false

- EC2 instance is not a public AMI. It's a custom image.
Let me know if you need any more information.

**Comment by andresbono** [comment]
@SudharsanN, can you share the container definition that you set for the container? Please make sure you don't expose your passwords if any when sharing it.

**Comment by SudharsanN** [comment]
@andresbono  Below is the entire task definition in JSON format which contains the Container definition too.

{
  "ipcMode": null,
  "executionRoleArn": "arn:aws:iam::703521142462:role/ecsTaskExecutionRole",
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "secretOptions": null,
        "options": {
          "awslogs-group": "/aws/ecs/djis-brs-dev/01",
          "awslogs-region": "us-east-1",
          "awslogs-stream-prefix": "jasperreports"
        }
      },
      "entryPoint": null,
      "portMappings": [
        {
          "hostPort": 8080,
          "protocol": "tcp",
          "containerPort": 8080
        }
      ],
      "command": null,
      "linuxParameters": null,
      "cpu": 0,
      "environment": [
        {
          "name": "APP_ENV",
          "value": "dev"
        },
        {
          "name": "JASPERREPORTS_DATABASE_NAME",
          "value": "brsreports"
        },
        {
          "name": "JASPERREPORTS_DATABASE_PASSWORD",
          "value": "******"
        },
        {
          "name": "JASPERREPORTS_DATABASE_USER",
          "value": "brsreports"
        },
        {
          "name": "JASPERREPORTS_EMAIL",
          "value": "BRS-Reports@dowjones.com"
        },
        {
          "name": "MARIADB_HOST",
          "value": "djis-billing-dev-brs-jasper-report-01.ccotnqed5ckq.us-east-1.rds.amazonaws.com"
        },
        {
          "name": "MARIADB_PORT_NUMBER",
          "value": "3306"
        },
        {
          "name": "MARIADB_ROOT_PASSWORD",
          "value": "******"
        },
        {
          "name": "MARIADB_ROOT_USER",
          "value": "brsreports"
        },
        {
          "name": "SMTP_EMAIL",
          "value": "BRS-Reports@dowjones.com"
        },
        {
          "name": "SMTP_HOST",
          "value": "10.13.32.134"
        },
        {
          "name": "SMTP_PASSWORD",
          "value": "test"
        },
        {
          "name": "SMTP_PORT",
          "value": "25"
        },
        {
          "name": "SMTP_PROTOCOL",
          "value": "smtp"
        },
        {
          "name": "SMTP_USER",
          "value": "BRS-Reports@dowjones.com"
        },
        {
          "name": "STACK",
          "value": "01"
        },
        {
          "name": "TZ",
          "value": "America/New_York"
        }
      ],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "703521142462.dkr.ecr.us-east-1.amazonaws.com/djis-brs-jasperreports-app:6",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "main"
    }
  ],
  "placementConstraints": [],
  "memory": "6144",
  "taskRoleArn": "arn:aws:iam::703521142462:role/djis-brs-dev-jasperreports-01-task",
  "compatibilities": [
    "EC2",
    "FARGATE"
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-east-1:703521142462:task-definition/djis-brs-dev-jasperreports-01:17",
  "family": "djis-brs-dev-jasperreports-01",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.ecr-auth"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-ecr-pull"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.task-eni"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [
    "EC2",
    "FARGATE"
  ],
  "networkMode": "awsvpc",
  "cpu": "1024",
  "revision": 17,
  "status": "ACTIVE",
  "inferenceAccelerators": null,
  "proxyConfiguration": null,
  "volumes": []
}

**Comment by andresbono** [comment]
Hi @SudharsanN, we couldn't reproduce the issue yet. Did you get any insights on your side?

Also, is it possible that the task-definition that you shared is based on another image instead of the bitnami one?

```
"image": "703521142462.dkr.ecr.us-east-1.amazonaws.com/djis-brs-jasperreports-app:6",
```

**Comment by SudharsanN** [comment]
@andresbono  
You tried it on ECS with EC2 and couldn't reproduce the issue ?

We changed the instance type of EC2 in ECS to be t2 large. After that we didn't notice the issue. As far as the image is concerned, it is of bitnami only. Just that we have an image on top of that.

On a different note, is LDAP based authentication possible with this image ?

**Comment by andresbono** [comment]
Hi @SudharsanN 

Yes, we tried on ECS, it should be related to the instance size then.

> On a different note, is LDAP based authentication possible with this image?

Unfortunately, it is not supported out of the box.

**Comment by SudharsanN** [comment]
Hi @andresbono 
For LDAP integration, following the steps mentioned in Jasper documents (also won't work? https://community.jaspersoft.com/documentation/jasperreports-authentication-cookbook/v56/ldap-authentication)

**Comment by andresbono** [comment]
It should work, but we haven't tested it. If you wan't, give it a try and let us know if you get stuck at some step. Maybe we can help.

Please, use this version of the documentation: https://community.jaspersoft.com/documentation/tibco-jasperreports-server-authentication-cookbook/v720/ldap-authentication (for `7.2.0`).
