### ISSUE TITLE
JasperReports does not recognize MongoDB response for an aggregation query.

### ISSUE THREAD

**Issue by ajmalshah88** [bitnami/bitnami-docker-jasperreports#71]
**Description**
JasperReports is unable to read MongoDB responses to aggregation queries, which is an obvious bug.

Link to issue:
[https://community.jaspersoft.com/jasperreports-server/issues/10886](https://community.jaspersoft.com/jasperreports-server/issues/10886)

**Steps to reproduce the issue:**

1. Build an aggregate query in studio for Mongodb 4.0 data source
2. Run report on server

**Describe the results you received:**

Error- no data loaded

**Additional information you deem important (e.g. issue happens only occasionally):**

https://community.jaspersoft.com/jasperreports-server/issues/10886#comment-860151

If anyone can advice on how to modify the docker image - particularly the JAR files as mentioned in the latest comments, I can test it and provide feedback.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi,
  You can enter the container and delete and add the files needed. The lib dir is `/opt/bitnami/jasperreports/WEB-INF/lib`, then [commit](https://docs.docker.com/engine/reference/commandline/commit/)  the modified container as a new image. And then use this new image in the docker-compose.yml.

**Comment by ajmalshah88** [comment]
Hi rafariossa,
Would there be a way to do it via dockerfile/script? 

I tried below:
FROM bitnami/jasperreports:7.2.0
RUN ls /opt/bitnami/jasperreports/WEB-INF/lib/ ---> returns no such file/directory

**Comment by rafariossaa** [comment]
In that case, you have to add the steps to be executed in the entrypoint, for example you can add them in the `app-entrypoint.sh` rigth after the `nami_initialize ... ` command.

**Comment by ajmalshah88** [comment]
works now. Thanks


rm  /opt/bitnami/jasperreports/WEB-INF/lib/js-mongodb-datasource-2.0.9.jar
rm /opt/bitnami/jasperreports/WEB-INF/lib/mongo-java-driver-3.3.0.jar
mv js-mongodb-datasource-3.10.2.jar /opt/bitnami/jasperreports/WEB-INF/lib/
mv mongo-java-driver-3.10.2.jar /opt/bitnami/jasperreports/WEB-INF/lib/

nami restart tomcat
