### ISSUE TITLE
Customizing the jasperserver configuration

### ISSUE THREAD

**Issue by sfergu** [bitnami/bitnami-docker-jasperreports#73]
I am wondering if anyone can point me in the right direction for documentation on how to customize the configuration of jaspersserver using this image. Specifically I want to turn on the json datasources in the configuration, so they will be available. I have attempted to update the files for that with a version my my own, but it is always overwritten by the one enclosed in the jasperserver war file. 

`COPY applicationContext-remote-services.xml /opt/bitnami/jasperreports/buildomatic/conf_source/ieCe/applicationContext-remote-services.xml
COPY applicationContext-remote-services.xml /opt/bitnami/jasperreports/WEB-INF/applicationContext-remote-services.xml`

neither of these work. that from the WEB-INF path is always overwritten with the one from the war file. 

Thanks!

**Comment by sfergu** [comment]
I was able to replace the entry for this file in the WAR file in my Dockerfile, but this seems brittle. Would like the best practice for this kind of customization

**Comment by javsalgar** [comment]
Hi,

Maybe an option to fix that could be allowing custom init scripts. We have been recently working on this so I'll update the ticket when the container has support for that.

**Comment by sfergu** [comment]
That sounds great. I could use that as well to load reports using REST. It would be a great feature.

**Comment by huang-tianwen** [comment]
@sfergu hi sfergu, how to copy those file at the end?
I need to customize the jasperserver to accept external login authentication, which i need to upload jar files to lib and applicationContexts files.

**Comment by klawhk** [comment]
I have such issue too. Actually I am studying how I can enable cluster for Jasperserver using Docker swarm, accordingly to the Jasperserver official documents, the following files have to be changed:

1. <web-app>/WEB-INF/web.xml
2. <tomcat>/conf/server.xml
3. <web-app>/WEB-INF/ehcache.xml

Do anyone have experience on that?

**Comment by huang-tianwen** [comment]
@klawhk my current solution is get the image from bitnami docker hub then copy modified app-entrypoint.sh to replace the existing one with code below

[#!/bin/bash -e

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/init.sh" ]]; then
    nami_initialize tomcat mysql-client jasperreports
    info "Starting git... "
    #copy all custom files at here because if we copy before initialization all change will gone or worst, get error
fi

exec tini -- "$@"
](url)

example from my dockerfile
FROM bitnami/jasperreports:7.2.0 AS base
COPY app-entrypoint.sh /
COPY resource files here to temporary directory which will be copied from app-entrypoint.sh code above

then host my own docker image.. if you want to use kubernetes, in bitnami/jasperreports chart you can change the image in values.yaml..

**Comment by rafariossaa** [comment]
Hi,
  I am creating an internal task to add support for init scripts in the image.
  We will come back to you as soon as we have news.

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-jasperreports#community-supported-solution) since this asset was marked as a "Community supported solution". At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
