### ISSUE TITLE
Error sending emails using gmail

### ISSUE THREAD

**Issue by dondragon2** [bitnami/bitnami-docker-jasperreports#75]
We are scheduling reports to be sent via a gmail account but the mails are not sent and the following exception is seen in the logs. We are running on kubernetes with the latest docker image.

```
530 5.7.0 Must issue a STARTTLS command first. q126sm5192757qkd.21 - gsmtp
```

**Comment by jotamartos** [comment]
Hi @dondragon2 ,

Thank you for using Bitnami. Could you please let us know more information about the issue? 

- What platform are you using to deploy in kubernetes?
- Did you set the environment variables to configure the SMTP settings?

https://github.com/bitnami/bitnami-docker-jasperreports#smtp-configuration

- Did you reproduce the same error using the docker image instead of the k8s deployment?

Thanks

**Comment by dondragon2** [comment]
Hi @jotamartos ,

I am using AWS EKS using the `kubectl` command line tool. Yes I set all those configurations but I am unable to set the `mail.smtp.starttls.enable=true`, which I believe is causing the issue. It is the same for docker because there is no way that I have seen to inject that property.

**Comment by mdhont** [comment]
Hi @dondragon2,

Can you connect to the pod with the following command:

> kubectl exec -ti JASPERREPORT_POD /bin/bash

And check if `mail.smtp.starttls.enable` property is set to true in the `/opt/bitnami/jasperreports/WEB-INF/applicationContext-report-scheduling.xml` file? If it's not, can you change it to `true` and check if that solves the issue? To edit the file you need to install an editor like vim using `install_packages vim`.

Thanks

**Comment by dondragon2** [comment]
Hi @mdhont,

the issue is that if the container is cycled or redeployed I will lose that configuration. There is no wait to inject this via env variable?

**Comment by dondragon2** [comment]
I think we can close this now. The value is set to true. I updated to the latest image and it seems to be fine now. I think the container was reading from the previous volume with an older version where this was not set.

**Comment by mdhont** [comment]
I'm glad to hear it's working now. We will keep investigating why the value wasn't set to true in the first place.
