### ISSUE TITLE
Can't deploy on Openshift

### ISSUE THREAD

**Issue by moray95** [bitnami/bitnami-docker-jasperreports#78]
**Description**

JasperReports Server deployed with the Bitnami Helm chart fails to start on Openshift with the following error message: `Cannot find any module matching the provided specification 'tomcat'`.

**Steps to reproduce the issue:**

Install the Bitnami JasperReports Server Helm chart on an Openshift cluster:
`helm install bitnami/jasperreports --set mariadb.securityContext.enabled=false`.

**Describe the results you received:**

The deployed container fails to start with the following error:
`Cannot find any module matching the provided specification 'tomcat'`.

**Describe the results you expected:**

The container starts up properly and I can access the web UI.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have seen similar issues on other Bitnami images (for example [WordPress](https://github.com/bitnami/bitnami-docker-wordpress/issues/127) and [DreamFactory](https://github.com/bitnami/bitnami-docker-dreamfactory/issues/5)), where the cause seems to be the image requiring root access, while it's not recommended nor enabled by default on Openshift.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Openshift 4.3

**Comment by marcosbc** [comment]
Hi @moray95, unfortunately OpenShift requires containers to be run by a non-root user and the Bitnami JasperReports container does not support that yet.

I will mark this as on-hold for now, but unfortunately won't be able to give an ETA for when this will be implemented, it will likely take months (or more).

If you prefer, you could contribute the changes so we include them in the Bitnami JasperReports container. You can find the JS initialization scripts in `/root/.nami/components/com.bitnami.jasperreports`. You can compare with other non-root containers how this was implemented (such as [WordPress](https://github.com/bitnami/bitnami-docker-wordpress)).
