### ISSUE TITLE
can't send e-mail from jasperreports

### ISSUE THREAD

**Issue by chris-fh** [bitnami/bitnami-docker-jasperreports#80]
first i got the error:
`Unknown SMTP host: mail.example.com`
even though i make use of the environment variables
```
      - SMTP_HOST=imap.fleuchaus.com
      - SMTP_PORT=587
      - SMTP_EMAIL=outgoing@fleuchaus.com
      - SMTP_USER=outgoing@fleuchaus.com
      - SMTP_PASSWORD=*****
      - SMTP_PROTOCOL=smtp
```
in docker-compose.yml

I found this help https://github.com/bitnami/bitnami-docker-jasperreports/issues/64

So after disabling the volume
`#      - 'jasperreports_data:/bitnami'`
i could only log in as user and not as any other user... but for the moment, just to see if i could make e-mail work, i left it like that.

then i got the following error
`Could not convert socket to TLS`
I thought i knew this. We are using a self-signed certificate on our mailserver. So i imported the certificate with keytool into /opt/bitnami/java/jre/lib/security/cacerts and will be using this line in docker compose to make it persistent:
```
    volumes:
      - /docker/jasperserver/cacerts:/opt/bitnami/java/jre/lib/security/cacerts
```

but now im stuck... the error still persists `Could not convert socket to TLS`

Does anyone know how to make e-mail work in the bitnami/jasperreports container?
Help will be most appreciated.

**Comment by javsalgar** [comment]
Hi,

I was able to configure SMTP by setting the env vars, but I don't know the steps to send a mail in JasperReports. Could you let us know the exact steps to reproduce the issue?

**Comment by chris-fh** [comment]
Hi,

you click on Home, on the left side choose "Reports" you make a right click with your mouse and select "Schedule". You click on "create schedule" (left, top) then you make some setting, like every 5 Minutes. Then you click on "notifications" (right, top) and you can enter a recipient for the e-mail.

![Bildschirmfoto 2020-07-31 um 14 20 36](https://user-images.githubusercontent.com/69001141/89035205-d72f8100-d33a-11ea-9c6d-2a2a751dc207.png)
![Bildschirmfoto 2020-07-31 um 14 21 41](https://user-images.githubusercontent.com/69001141/89035208-d860ae00-d33a-11ea-9503-4e8d3f94b9e3.png)
![Bildschirmfoto 2020-07-31 um 14 24 09](https://user-images.githubusercontent.com/69001141/89035210-d8f94480-d33a-11ea-8c53-7ff2f6c9ae9d.png)


I added some screenshots (sorry they are in german language)

I was finally able to solve my problem. The environment variables remain without effect. I entered the container (docker exec -it xxx bash). I edited a file contained in the persistent part of the filesystem (the volume jasperreports_data:/bitnami).
the filename was `/bitnami/jasperreports/buildomatic/default_master.properties`
I added the following lines:
```
quartz.mail.sender.host=imap.fleuchaus.com
quartz.mail.sender.from=outgoing@fleuchaus.com
quartz.mail.sender.username=uname
quartz.mail.sender.password=**********
```
from there on it worked like a charm.

**Comment by joancafom** [comment]
Hi @chris-fh !

Happy to hear everything worked like a charm eventually! 😁  Do you need any further assistance on this? Please, do not hesitate to open a new issue if you find any other problem, we'd love to give a hand and help you out!

Thanks!

**Comment by chris-fh** [comment]
Hi joancafom,

No i do not need any further assistance on this. I'm closing the issue.

Thank you!
