### ISSUE TITLE
Keycloak integration

### ISSUE THREAD

**Issue by juanvasquezreyes** [bitnami/bitnami-docker-jasperreports#82]
Will be nice to have keycloak integration in the docker image and also be able to use the same in HELM

https://github.com/ramunask/jasperserver-war-keycloak

**Comment by dani8art** [comment]
Hi @juanvasquezreyes, thank you so much for your suggestion. 

We try to make generic production images that people can extend easily if it would be needed. We were reviewing this integration and it seems to be a very specific case. Also, the github project that you have posted seems to be not maintained, it has only 4 commits and the last one was on 31 mar 2016. 

However, you can use our image as base on your own and extend it adding this integration.

```
FROM bitnami/jasperreports:7.8.0

COPY ...

RUN ...
```

Regards.
