### ISSUE TITLE
Jasperreports deployed via Helm Chart doesn't restart correctly

### ISSUE THREAD

**Issue by ugoviti** [bitnami/bitnami-docker-jasperreports#84]
**Description**
Running on GKE + Helm Chart

deployed latest version:

```
NAME                    NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                   APP VERSION
jasperreports           test            12              2020-10-14 18:31:11.344763655 +0200 CEST        deployed        jasperreports-8.0.5     7.8.0
```

on container restart the file `/bitnami/jasperreports/buildomatic/default_master.properties` get modified from these lines:

```
maven.jdbc.version=2.5.3
```

to:

```
maven\.jdbc\.version=2.5.3
```

and after the first restart, the container doesn't start anymore returning:

```
Error executing 'postInstallation': Error: File /bitnami/jasperreports/buildomatic/default_master.properties did not match any of the provided substitutions
```
only editing the `default_master.properties` file make bitnami/jasperreports works again:

`sed 's/\\\././g' -i /bitnami/jasperreports/buildomatic/default_master.properties`

**Steps to reproduce the issue:**

1. `helm install jasperreports bitnami/jasperreports`
2. delete the pod
3. wait jasperreport come online and delete again
4. the pod doesn't start anymore

**Describe the results you received:**

**Describe the results you expected:**

the file `default_master.properties` don't get modified

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
$ kubectl get nodes -o wide
NAME                          STATUS   ROLES    AGE   VERSION            INTERNAL-IP   EXTERNAL-IP      OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
gke-XXXXXXXX   Ready    <none>   16h   v1.16.13-gke.401   XX.XX.0.5    XX.XX.XXX.XXX    Ubuntu 18.04.5 LTS   5.3.0-1036-gke   docker://19.3.2
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

tested against image:

`docker.io/bitnami/jasperreports:7.8.0-debian-10-r11`

Let's me know if you need other info.

Thank you for the support.

Kind Regards

**Comment by andresbono** [comment]
Hi @ugoviti, thanks for reporting this issue. We will try to reproduce it and we will get back to you.

**Comment by andresbono** [comment]
Hi @ugoviti, we have included a fix for this bug in the latest image of the container. Could you please use it and let us know if it works for you?

- Container image: `bitnami/jasperreports:7.8.0-debian-10-r39` https://github.com/bitnami/bitnami-docker-jasperreports/commit/0708f7968f85ff9bed69abac9be198d58ff32364
- Helm chart: `bitnami/jasperreports` `8.0.6` https://github.com/bitnami/charts/commit/a9e45b4a113076c0bdb47e4997371902aba189fd

**Comment by ugoviti** [comment]
Hi,

thank you for the quick reply.

Tested and I confirm the bug is solved now.

Kind Regards

**Comment by andresbono** [comment]
Thanks for confirming it!
