### ISSUE TITLE
Tomcat admin without password

### ISSUE THREAD

**Issue by mrcobol** [bitnami/bitnami-docker-jasperreports#85]
**Description**

The tomcat server included in the container has default admin user "user" with no password. Outside access with administrative privileges to admin gui is possible.
User should be disabled or have random password. 

**Steps to reproduce the issue:**

1. Install jasperreports docker container and run it
2. Load http://localhost:8080/manager/html in your browser
3. User is "user" password ist blank

**Describe the results you received:**

Access to administrative gui is granted

**Describe the results you expected:**

Access to administrative gui should not be granted out of the box or a random password should be set for this user in the tomcat-users.xml file

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue has been actively used to upload some unknown program to a server running jasperreports

**Comment by alemorcuq** [comment]
Hi, @mrcobol.

The manager is not accessible from the outside:

```
root@0c0c0d53c88f:/# cat opt/bitnami/tomcat/webapps/manager/META-INF/context.xml
<?xml version="1.0" encoding="UTF-8"?>
...
<Context antiResourceLocking="false" privileged="true" >
  <CookieProcessor className="org.apache.tomcat.util.http.Rfc6265CookieProcessor"
                   sameSiteCookies="strict" />
  <Valve className="org.apache.catalina.valves.RemoteAddrValve"
         allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" />
...
```

Isn't this the case for you as well?

**Comment by mrcobol** [comment]
Hi @alemorcuq,
I am sorry. You are right. The older version of the jasperreports container where our issue happened did not have the filter for local connections.
Assigning a random password or forcing users of this container to set a password before using might still be a good idea so not everyone with access to the server is tomcat administrator.

Regards

**Comment by alemorcuq** [comment]
I agree with you. I'm going to create an internal task to provide some environment variables for setting the manager credentials.

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-jasperreports#community-supported-solution) since this asset was marked as a "Community supported solution". At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
