### ISSUE TITLE
Change jasper server base url

### ISSUE THREAD

**Issue by MaitreDede** [bitnami/bitnami-docker-jasperreports#88]
Hello,

According to [the docs](https://community.jaspersoft.com/wiki/best-practices-deploying-jasperreports-server-your-web-application), to serve jasper server, the reverse proxy url must match the tomcat url.

I would like to know when I should start to change some scripts/config, to server jasper server from arbitrary path.

**Comment by miguelaeh** [comment]
Hi @MaitreDede ,
I am sorry I am not sure to understand the question. Could you describe what are you trying to achieve?

**Comment by MaitreDede** [comment]
Hi @miguelaeh 

I need to serve jasper server through a reverse proxy, but with a different path that does not match the tomcat one. But according to the docs, the reverse proxy path must match the tomcat path...

For example, I have two jasper reports instances, with 2 different ip addresses. I would like to expose both on same reverse proxy : /jasper/first and /jasper/second. But these path don't match tomcat path that is /jasperserver. And I tested a simple nginx reverse proxy, dis not work. I always get redirected to tomcat's path.

One solution would be to allow to change the tomcat url of jasperserver, so I can match the reverse proxy.

I tried some modifications of docker script and files, but the path seams hardcoded deeply and some scripts are failing...

**Comment by miguelaeh** [comment]
Hi @MaitreDede ,
Thank you for the clarification, I understand it now.
I would say you can configure your proxy as you want. I mean, you coud have two jasperserver instances running each one at `a.a.a.a/jasperserver` and `b.b.b.b/jasperserver` and configure your proxy to redirect the request depending on the path, for example like:
`proxyUrl/a` -> `a.a.a.a/jasperserver`
`proxyUrl/b` -> `b.b.b.b/jasperserver`

Did you try that configuration?

**Comment by MaitreDede** [comment]
That is exactly what I tried, with a nginx reverse proxy.

As stated in the documentation : https://community.jaspersoft.com/wiki/best-practices-deploying-jasperreports-server-your-web-application#Proxy_definitions_for_JasperReports_Server
```
# These will not work: proxy path does not match JasperReports Server path
```

So until there is a simple solution to configure the jasperserver path (or that permits easy reverse proxy scenarii), I have written a small reverse proxy that handles headers and content for path changing. It is like the apache module `mod_substitute`.

**Comment by miguelaeh** [comment]
Hi @MaitreDede ,
In that case, in jasperserver you can change the path by renaming the directory. Check this: https://community.jaspersoft.com/wiki/changing-jasperreports-server-url

You could try to use a diferent path for each instance like:
```
proxyUrl/servera -> a.a.a.a/servera
proxyUrl/serverb -> b.b.b.b/serverb
```
