### ISSUE TITLE
Does this image support HA setup/scaling ?

### ISSUE THREAD

**Issue by shyamjos** [bitnami/bitnami-docker-jasperreports#90]
I am planning to deploy jasper server in kubernetes cluster using bitnami helm chart and I wanted to know whether this image support scaling (HPA)? If not, what is the best way to achieve scaling/HA for Jasper reports ?

**Comment by Mauraza** [comment]
Hi @shyamjos,

the container in principle it supports HPA, although the helm chart of JasperReports doesn't have implemented this.
The MariaDB of the chart (JasperReports) has the option of replication, but I don't know if that is enough for you.

**Comment by shyamjos** [comment]
We want to scale Jasper Reports container (increase replica count ) based on load, but when we manually scaled the deployment to 2 replicas the applications keeps logging out automatically , Not sure if this is because jasper server not support shared session? Seems like we need to enable a sticky cookie in our ingress.

**Comment by Mauraza** [comment]
Hi @shyamjos,

I was investigating a little more and I found this https://github.com/bitnami/charts/pull/201#discussion_r90387932, 
> the replicas field since horizontal scaling of the jasperserver pod is not supported
It seems JasperReports do not support HPA, sorry.

**Comment by shyamjos** [comment]
But somehow we were able to run it with more than 1 replica and sticky session, Anyway is there any other way to achieve scalability ?

**Comment by Mauraza** [comment]
Maybe you can use a load balancer with the session sticky session to redirect the user with a session to the same node.
