### ISSUE TITLE
Jasper reports can not connect to DB 

### ISSUE THREAD

**Issue by AndrewJRamay** [bitnami/bitnami-docker-jasperreports#93]
Hi, I can not get the jasper reports container to connect to any database. it will sit and try for a while then fail and turn itself off. I have tried using the MariaDB that is recommended in the same docker network environment. I have tried using an external network connection nothing will work. please help.

**Comment by marcosbc** [comment]
Hi @AndrewJRamay, could you share your `docker-compose.yml` or the `docker run` commands that you are using? Note that you can find a working docker-compose here: https://github.com/bitnami/bitnami-docker-jasperreports/blob/master/docker-compose.yml
