### ISSUE TITLE
When I customize Dockerfile and spin up the image, the container is not connecting to the database

### ISSUE THREAD

**Issue by DaniyalAkbar** [bitnami/bitnami-docker-jasperreports#98]
I want to build my own image and run the container of only jasperreports. Not using docker-compose for this. 
In doing that, I'm getting an error when I run the container. When I check the logs through command "docker logs jasperreports", it shows the error as this:
### Error
![image](https://user-images.githubusercontent.com/38786176/130789420-176f1ef6-f66b-4f59-826d-05d5ce5a71aa.png)

I want to install the Webservice Datasource plugin in JasperReport Server. I'm following the setup from this link. https://community.jaspersoft.com/wiki/installing-webservice-datasource 

So, the only addition to your Dockerfile is a few COPY commands to copy the plugin files to WEB-INF folder of your container.
 ### This is the final version of the updated Dockerfile. 

![tempsnip](https://user-images.githubusercontent.com/38786176/130792081-1afa9918-4b68-48a1-b1ed-0deae15901b2.png)

 
After I build the image, I run the docker container using this command script:

docker run -d --name jasperreports \
  -p 8088:8089 -p 8443:8443 \
  --env ALLOW_EMPTY_PASSWORD=yes \
  --env JASPERREPORTS_DATABASE_USER=bn_jasperreports \
  --env JASPERREPORTS_DATABASE_PASSWORD=bitnami \
  --env JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports \
  --env JASPERREPORTS_USERNAME=jasperadmin \
  --env JASPERREPORTS_PASSWORD=jasperadmin \
  --network jasperreports-network \
  --volume jasperreports_data:/bitnami/jasperreports \
  bitnami_image_webservice:latest

**Comment by javsalgar** [comment]
Could you add the `BITNAMI_DEBUG=true` env var to the JasperReports container to see if it provides any extra information?

**Comment by DaniyalAkbar** [comment]
When i add `BITNAMI_DEBUG=true` it shows following in the logs:

![image](https://user-images.githubusercontent.com/38786176/131317766-b8e8e829-3a98-4f5b-a9b5-3c6ad5f82ffa.png)

**Comment by javsalgar** [comment]
Ok, so it seems clear to me that the mariadb instance is missing. Do you have a MariaDB instance running with the dns name `mariadb`?

**Comment by DaniyalAkbar** [comment]
i have this mariaDB instance running through docker 

![image](https://user-images.githubusercontent.com/38786176/131467750-5a3ecbbd-550c-4769-a2ef-cec090014263.png)

**Comment by javsalgar** [comment]
Hi,

So it seems to me that this instance is not in the same container network as the JasperReports instance. That would explain that the JasperReports instance cannot resolve the mariadb. Could you check the docker networks of each instance?

**Comment by DaniyalAkbar** [comment]
Hey, 
You were right!
So the network on which the mariadb instance was running, was different from the network jasperreport server I was trying to run. I checked the docker network list and found the network name on which mariadb was running on. So I added a network env variable in the `docker run` script for the JasperRerport Server container. Its not giving me the DB error **but the build is still failing.** 

### This is the Error
![image](https://user-images.githubusercontent.com/38786176/131663062-bcaec706-98cb-48f0-bbdc-f6fe7867dd8a.png)



The network on which mariadb instance was running is **jasperservernew_default** 
and my final `docker run` script is this:

```
docker run -d --name jasperreports_da\
  -p 8088:8089 -p 8443:8443\
  --env ALLOW_EMPTY_PASSWORD=yes\
  --env JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports\
  --env JASPERREPORTS_DATABASE_HOST=mariadb\
  --env JASPERREPORTS_DATABASE_USER=bn_jasperreports\
  --env JASPERREPORTS_DATABASE_PASSWORD=bitnami\
  --env JASPERREPORTS_DATABASE_PORT_NUMBER=3306\
  --env JASPERREPORTS_USERNAME=jasperadmin\
  --env JASPERREPORTS_PASSWORD=jasperadmin\
  --env BITNAMI_DEBUG=true\
  --network jasperservernew_default\
  --volume jasperreports_data:/bitnami/jasperreports\
  bitnami_image_webservice:latest
```

**Comment by javsalgar** [comment]
Could it be that the volume is using leftovers of a previous installation? I mean the `jasperreports_data` one. Would it be possible to clean it?

**Comment by DaniyalAkbar** [comment]
okay i tried a few things, none of them worked. I have a few questions though...
1. Does the volume mounted need to be the same for both JasperReport Server and MariaDB instance?
2. Whats actions is it performing with the mounted volume?


What I tried this time was to remove the `jasperreports_data` volume from my server. I assumed that would have removed all the data it held. Then I ran my `docker run` script so that it would make a fresh volume mount of `jasperreports_data`. When I did that, it gave me a different error: 

![image](https://user-images.githubusercontent.com/38786176/132164630-7b9b73ff-d8bc-4048-9ecf-22e934c5f79e.png)


Then I inspected the mariaDB docker instance that was running to find the volume it had mounted. The volume name was `jasperservernew_mariadb_data`. So I replaced that name in my script. So then my updated `docker run` script was this: 

```docker run -d --name jasperreports_da\
  -p 8088:8089 -p 8443:8443\
  --env ALLOW_EMPTY_PASSWORD=yes\
  --env JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports\
  --env JASPERREPORTS_DATABASE_HOST=mariadb\
  --env JASPERREPORTS_DATABASE_USER=bn_jasperreports\
  --env JASPERREPORTS_DATABASE_PASSWORD=bitnami\
  --env JASPERREPORTS_DATABASE_PORT_NUMBER=3306\
  --env JASPERREPORTS_USERNAME=jasperadmin\
  --env JASPERREPORTS_PASSWORD=jasperadmin\
  --env BITNAMI_DEBUG=true\
  --network jasperservernew_default\
  --volume jasperservernew_mariadb_data:/bitnami/jasperreports\
  bitnami_image_webservice:latest
```
But this didn't spun up my JasperReport Server container either. The logs showed me this: 

![image](https://user-images.githubusercontent.com/38786176/132164883-ad4022cc-26ca-4cba-a967-e98c9a57749b.png)

What should I do now?

**Comment by pablogalegoc** [comment]
> Does the volume mounted need to be the same for both JasperReport Server and MariaDB instance?

Each container should use its own volume

> Whats actions is it performing with the mounted volume?

For JasperReports, if it finds the volume directory is not empty then assumes it has to restore a previous installation:
https://github.com/bitnami/bitnami-docker-jasperreports/blob/15679f89a3b27edca0427eb7ff521a28d5c0d19b/7/debian-10/prebuildfs/opt/bitnami/scripts/libpersistence.sh#L114-L118
Restoring the previous installation has two parts, restoring JasperReports data and connecting to the database:
https://github.com/bitnami/bitnami-docker-jasperreports/blob/1e36b16ebf6f93699e6f00eca75f6beee1ae3eba/7/debian-10/rootfs/opt/bitnami/scripts/libjasperreports.sh#L292-L305
In your case it seems to be failing in the first part. It thinks there's a previous installation but when trying to restore its files fails to find `default_master.properties`.

**Comment by DaniyalAkbar** [comment]
So now what do i do?

Should I create a fresh JasperReport Server image and spin up the container with a different volume name to mount?

**Comment by javsalgar** [comment]
I think that using a fresh volume for each of them should work, could you confirm they are fresh volumes?

**Comment by DaniyalAkbar** [comment]
i didn't change anything for the mariaDB instance. 
but for the custom image that I built for jasperReport server, I change the name of the volume when I execute the `docker run` script that I've mentioned before. Does that mean a fresh volume?

**Comment by javsalgar** [comment]
If the logs specify that it is deploying from scratch, yes it should be interpreted as a fresh volume.
